replicaCount: 1

image:
  repository: jrebaza01/nats-subscriber
  tag: "54"
  pullPolicy: Always

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

probes:
  enabled: false
